#!/usr/bin/env python

import sys
import os
sys.path.append(os.path.abspath("../"))
sys.path.append(os.path.abspath("."))
from blkdiscovery import BlkDiscovery

import pprint

pp = pprint.PrettyPrinter(indent=4)
bd = BlkDiscovery()
disks = bd.disks()
pp.pprint(disks)
devdata = bd.details()
pp.pprint(devdata)
